name: CMake Build Matrix

on: [push]

jobs:
  build:
        
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: 
        config: 
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.7z",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            list_files: "Get-ChildItem -Path . -Recurse"
          }
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++",
            list_files: ls -l
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++",
            list_files: ls -l
          }

    steps:    
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Check cmake version
      run: |
        cmake --version  
    
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: 1.73.0
        
    - name: cmake_crashkurs
      working-directory: CMake/cmake_crashkurs
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: cmake_cpp_standard_ex1
      working-directory: CMake/cmake_cpp_standard/Beispiel_1/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_cpp_standard_ex2
      working-directory: CMake/cmake_cpp_standard/Beispiel_2/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_cpp_standard_ex3
      working-directory: CMake/cmake_cpp_standard/Beispiel_3/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_cpp_standard_ex4
      working-directory: CMake/cmake_cpp_standard/Beispiel_4/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_libraries_ex1
      working-directory: CMake/cmake_libraries/Beispiel_1/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

#   - name: Archive build files 
#      uses: actions/upload-artifact@v3
#      with:
#        name: build_files_${{ matrix.config.name }}
#        path: CMake/cmake_libraries/Beispiel_1/build
    
    - name: cmake_libraries_ex2_shared
      working-directory: CMake/cmake_libraries/Beispiel_2/Shared
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        
    - name: cmake_libraries_ex2_static
      working-directory: CMake/cmake_libraries/Beispiel_2/Static
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        
    - name: cmake_libraries_ex3
      working-directory: CMake/cmake_libraries/Beispiel_3/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_libraries_ex4
      working-directory: CMake/cmake_libraries/Beispiel_4/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_libraries_ex5
      working-directory: CMake/cmake_libraries/Beispiel_5/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    
    - name: cmake_libraries_ex6
      working-directory: CMake/cmake_libraries/Beispiel_6/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_variables_ex1
      working-directory: CMake/cmake_variables/Beispiel_1/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_variables_ex2
      working-directory: CMake/cmake_variables/Beispiel_2/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_variables_ex3
      working-directory: CMake/cmake_variables/Beispiel_3/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: cmake_variables_ex4
      working-directory: CMake/cmake_variables/Beispiel_4/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
